Repository DeveloperAcademy-POSTECH/MC3-Team5-CleanArea, pull requests merged in 2023-07, with the labels that each got.

#3 Feature/#2 - 프로젝트 세팅
  .DS_Store
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Yeowoo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Yeowoo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Yeowoo/Assets.xcassets/AccentColor.colorset/Contents.json
  Yeowoo/Assets.xcassets/AppIcon.appiconset/Contents.json
  Yeowoo/Assets.xcassets/Contents.json
  Yeowoo/Info.plist
  Yeowoo/Preview Content/Preview Assets.xcassets/Contents.json
  Yeowoo/Sources/ContentView.swift
  Yeowoo/YeowooApp.swift
  YeowooTests/YeowooTests.swift
  YeowooUITests/YeowooUITests.swift
  YeowooUITests/YeowooUITestsLaunchTests.swift
Labels: ⚙️ 설정

#6 단어 수정 #5
  Yeowoo/Sources/ContentView.swift
Labels: ✨ 기능

#9 로그인, 회원가입 로직을 구현
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Sources/Models/User.swift
  Yeowoo/Sources/Services/Firebase/FirebaseError.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/Services/FirebaseService.swift
  Yeowoo/Sources/Services/KeyChain/KeyChainAccount.swift
  Yeowoo/Sources/Services/KeyChain/KeyChainError.swift
  Yeowoo/Sources/Services/KeyChain/KeyChainManager.swift
Labels: ✨ 기능

#12 Firebase User CRUD
  Yeowoo/Sources/Models/User.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
Labels: ✨ 기능

#13 Firebase Album CRUD
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
Labels: ✨ 기능

#19 #7
  .DS_Store
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/ButtonColor.colorset/Contents.json
  Yeowoo/Assets.xcassets/CameraButton.imageset/CameraButton.svg
  Yeowoo/Assets.xcassets/CameraButton.imageset/Contents.json
  Yeowoo/Assets.xcassets/RoleButton.imageset/Contents.json
  Yeowoo/Assets.xcassets/RoleButton.imageset/RoleButton.svg
  Yeowoo/Assets.xcassets/WriteButton.imageset/Contents.json
  Yeowoo/Assets.xcassets/WriteButton.imageset/WriteButton.svg
  Yeowoo/Assets.xcassets/YeowooNavigation.imageset/Contents.json
  Yeowoo/Assets.xcassets/YeowooNavigation.imageset/YeowooNavigation.svg
  Yeowoo/Sources/Global/Font+.swift
  Yeowoo/Sources/Global/UIScreen+.swift
  Yeowoo/Sources/ViewModels/CameraViewModels/CameraViewModel.swift
  Yeowoo/Sources/Views/CameraViews/Buttons.swift
  Yeowoo/Sources/Views/CameraViews/CameraButtonView.swift
  Yeowoo/Sources/Views/CameraViews/Components/FeatureButton.swift
  Yeowoo/Sources/Views/CameraViews/Components/RoleButton.swift
  Yeowoo/Sources/Views/CameraViews/EditView.swift
  Yeowoo/Sources/Views/CameraViews/RoleView.swift
  Yeowoo/Sources/Views/CameraViews/WriteTextView.swift
  Yeowoo/YeowooApp.swift
Labels: 💄 UI, ✨ 기능

#27 앨범 페이지 가이드 제작
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Sources/ContentView.swift
  Yeowoo/Sources/Models/Album.swift
  Yeowoo/Sources/Models/Test.swift
  Yeowoo/Sources/Models/User.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/ViewModels/TestViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/AlbumView.swift
  Yeowoo/Sources/Views/Album/Layouts/FirstFeedLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/GalleryLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/SecondFeedLayout.swift
  Yeowoo/Sources/Views/TestView.swift
Labels: 💄 UI, ✨ 기능

#29 로그인 및 회원가입 페이지 제작
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/B1.colorset/Contents.json
  Yeowoo/Assets.xcassets/G2.colorset/Contents.json
  Yeowoo/Assets.xcassets/G3.colorset/Contents.json
  Yeowoo/Assets.xcassets/G4.colorset/Contents.json
  Yeowoo/Assets.xcassets/G5.colorset/Contents.json
  Yeowoo/Assets.xcassets/G6.colorset/Contents.json
  Yeowoo/Assets.xcassets/R1.colorset/Contents.json
  Yeowoo/Assets.xcassets/logincover.imageset/Contents.json
  Yeowoo/Assets.xcassets/logincover.imageset/logincover.png
  Yeowoo/Assets.xcassets/여우.imageset/Contents.json
  Yeowoo/Assets.xcassets/여우.imageset/여우.png
  Yeowoo/Sources/Views/LoginCoverView.swift
  Yeowoo/Sources/Views/LoginView.swift
  Yeowoo/Sources/Views/SignUpView.swift
  Yeowoo/YeowooApp.swift
Labels: 💄 UI, ✨ 기능

#32 앨범 파이어베이스 구조 수정
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Sources/ContentView.swift
  Yeowoo/Sources/Global/String+.swift
  Yeowoo/Sources/Models/Album.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/Layouts/GalleryLayout.swift
Labels: ♻️ 리팩토링, ⚙️ 설정

#37 앨범 페이지 좋아요 기능 및 구조 수정
  Yeowoo/Sources/Global/String+.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/Services/UserDefaults/UserDefaultsSetting.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
  Yeowoo/Sources/Views/Album/Layouts/FirstFeedLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/GalleryLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/SecondFeedLayout.swift
Labels: 💄 UI, ✨ 기능

#38 앨범 이미지 상세 페이지 메뉴 기능 구현
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/CaesarComponents/View/Role/InvitationChildView/MultiInvitationView.swift
  Yeowoo/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/Sources/ContentView.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
Labels: ✨ 기능, ⚙️ 설정

#43 로그인 및 회원가입 데이터 연결
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Sources/Global/View+.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AuthViewModel.swift
  Yeowoo/Sources/Views/Auth/LoginCoverView.swift
  Yeowoo/Sources/Views/Auth/LoginView.swift
  Yeowoo/Sources/Views/Auth/SignUpView.swift
  Yeowoo/Sources/Views/LoginView.swift
  Yeowoo/Sources/Views/SignUpView.swift
  Yeowoo/YeowooApp.swift
Labels: ✨ 기능

#45 이미지 상세 페이지 메뉴 기능 구현 및 연결
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/Album/Contents.json
  Yeowoo/Assets.xcassets/Album/activityFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/activityFox.imageset/activityFox.svg
  Yeowoo/Assets.xcassets/Album/captainFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/captainFox.imageset/captainFox.svg
  Yeowoo/Assets.xcassets/Album/chk.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/chk.imageset/chk.svg
  Yeowoo/Assets.xcassets/Album/eatFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/eatFox.imageset/eatFox.svg
  Yeowoo/Assets.xcassets/Album/normalFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/normalFox.imageset/normalFox.svg
  Yeowoo/Assets.xcassets/Album/paparazziFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/paparazziFox.imageset/paparazziFox.svg
  Yeowoo/Assets.xcassets/Album/sceneryFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/sceneryFox.imageset/sceneryFox.svg
  Yeowoo/Sources/ContentView.swift
  Yeowoo/Sources/Global/UINavigationController+.swift
  Yeowoo/Sources/Models/Album.swift
  Yeowoo/Sources/Models/User.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
  Yeowoo/Sources/Views/Album/Layouts/FirstFeedLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/GalleryLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/SecondFeedLayout.swift
Labels: ♻️ 리팩토링, ✨ 기능

#47 새 앨범 만들기 데이터 연결
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/CaesarComponents/Component/FindFriendContents.swift
  Yeowoo/CaesarComponents/Component/FoxCardView.swift
  Yeowoo/CaesarComponents/Model/MockupDataModel/Fox.swift
  Yeowoo/CaesarComponents/View/NewAlbum/AlbumRoleSelectView.swift
  Yeowoo/CaesarComponents/View/NewAlbum/FindFriendView.swift
  Yeowoo/CaesarComponents/View/NewAlbum/NewAlbumView.swift
  Yeowoo/CaesarComponents/View/Root/DemoMainView.swift
  Yeowoo/CaesarComponents/ViewModel/FindFriendViewModel.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/Views/Auth/SignUpView.swift
  Yeowoo/YeowooApp.swift
Labels: ♻️ 리팩토링, ✨ 기능

#50 앨범 페이지 상세 세팅 + UT 피드백 적용
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/CaesarComponents/View/Root/DemoMainView.swift
  Yeowoo/Sources/Global/CacheAsyncImage.swift
  Yeowoo/Sources/Models/Album.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
  Yeowoo/Sources/Views/Album/Layouts/FirstFeedLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/GalleryLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/SecondFeedLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
Labels: ♻️ 리팩토링, ✨ 기능

#52 마이페이지 데이터 연결
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/CaesarComponents/View/PersonalSetting/ProfileSettingView.swift
  Yeowoo/CaesarComponents/View/PersonalSetting/SettingView.swift
  Yeowoo/CaesarComponents/View/Root/DemoMainView.swift
  Yeowoo/CaesarComponents/ViewModel/SettingViewModel.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/Views/Auth/LoginCoverView.swift
Labels: ✨ 기능

#54 로컬 노티 + FCM 기능 구현 1차
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/AccentColor.colorset/Contents.json
  Yeowoo/Assets.xcassets/Album/Contents.json
  Yeowoo/Assets.xcassets/Album/activityFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/activityFox.imageset/activityFox.svg
  Yeowoo/Assets.xcassets/Album/captainFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/captainFox.imageset/captainFox.svg
  Yeowoo/Assets.xcassets/Album/eatFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/eatFox.imageset/eatFox.svg
  Yeowoo/Assets.xcassets/Album/normalFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/normalFox.imageset/normalFox.svg
  Yeowoo/Assets.xcassets/Album/paparazziFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/paparazziFox.imageset/paparazziFox.svg
  Yeowoo/Assets.xcassets/Album/sceneryFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Album/sceneryFox.imageset/sceneryFox.svg
  Yeowoo/Assets.xcassets/Role/chk.imageset/Contents.json
  Yeowoo/Assets.xcassets/Role/chk.imageset/chk.svg
  Yeowoo/Assets.xcassets/여우.imageset/Contents.json
  Yeowoo/Assets.xcassets/여우.imageset/여우.png
  Yeowoo/CaesarComponents/Model/MockupDataModel/SubUser.swift
  Yeowoo/CaesarComponents/View/NewAlbum/FindFriendView.swift
  Yeowoo/CaesarComponents/View/NewAlbum/NewAlbumView.swift
  Yeowoo/CaesarComponents/View/Notification/NotiChildView/NotificationView.swift
  Yeowoo/CaesarComponents/View/Notification/Notification.swift
  Yeowoo/CaesarComponents/View/Notification/NotificationViewModel.swift
  Yeowoo/CaesarComponents/View/Role/InvitationChildView/MultiInvitationView.swift
  Yeowoo/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/CaesarComponents/View/Role/InvitationView.swift
  Yeowoo/CaesarComponents/View/Role/RoleChangeView.swift
  Yeowoo/CaesarComponents/View/Role/RoleSelectView.swift
  Yeowoo/CaesarComponents/ViewModel/FindFriendViewModel.swift
  Yeowoo/CaesarComponents/ViewModel/InvitationViewModel.swift
  Yeowoo/Configuration/AppDelegate.swift
  Yeowoo/Info.plist
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/Services/UserDefaults/UserDefaultsSetting.swift
  Yeowoo/Sources/TestNoti/NotiTestView.swift
  Yeowoo/Sources/TestNoti/NotificationDelegate.swift
  Yeowoo/Sources/TestNoti/NotificationHandler.swift
  Yeowoo/Sources/TestNoti/Push.swift
  Yeowoo/Sources/TestNoti/Schedule.swift
  Yeowoo/Sources/TestNoti/Test2.swift
  Yeowoo/Sources/Views/Auth/LoginCoverView.swift
  Yeowoo/YeowooApp.swift
Labels: ✨ 기능

#55 임시 머지
  .DS_Store
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/.DS_Store
  Yeowoo/Sources/CaesarComponents/Component/BackToolBarModifier.swift
  Yeowoo/Sources/CaesarComponents/Component/CardViewModifier.swift
  Yeowoo/Sources/CaesarComponents/Component/EditProfileRowView.swift
  Yeowoo/Sources/CaesarComponents/Component/FindFriendContents.swift
  Yeowoo/Sources/CaesarComponents/Component/FoxCardView.swift
  Yeowoo/Sources/CaesarComponents/Component/GrayTitleMakingView.swift
  Yeowoo/Sources/CaesarComponents/Component/NotiCardContentsView.swift
  Yeowoo/Sources/CaesarComponents/Component/TextFieldModifier.swift
  Yeowoo/Sources/CaesarComponents/Model/ColorModel.swift
  Yeowoo/Sources/CaesarComponents/Model/Font.swift
  Yeowoo/Sources/CaesarComponents/Model/MockupDataModel/Fox.swift
  Yeowoo/Sources/CaesarComponents/Model/MockupDataModel/SubUser.swift
  Yeowoo/Sources/CaesarComponents/Model/MockupDataModel/Travel.swift
  Yeowoo/Sources/CaesarComponents/Model/ScreenModel.swift
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/AlbumRoleSelectView.swift
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/FindFriendView.swift
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/NewAlbumView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/EmptyNotificationView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NotiView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NoticardView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NotificationView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiView.swift
  Yeowoo/Sources/CaesarComponents/View/PersonalSetting/ProfileSettingView.swift
  Yeowoo/Sources/CaesarComponents/View/PersonalSetting/SettingView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/MultiInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleChangeView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleSelectView.swift
  Yeowoo/Sources/CaesarComponents/View/Root/DemoMainView.swift
  Yeowoo/Sources/CaesarComponents/ViewModel/FindFriendViewModel.swift
  Yeowoo/Sources/ViewModels/MainViewModel/MainViewModel.swift
  Yeowoo/Sources/Views/CameraViews/EditView.swift
  Yeowoo/Sources/Views/CameraViews/RoleView.swift
  Yeowoo/Sources/Views/CameraViews/WriteTextView.swift
  Yeowoo/Sources/Views/Main/Components/TapePicture.swift
  Yeowoo/Sources/Views/Main/Layouts/AlbumLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/BeforeTravelLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/DoneTravelLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/RecommendLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
  Yeowoo/YeowooApp.swift
Labels: 💄 UI, ♻️ 리팩토링, ✨ 기능

#59 알림 로직 수정
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/CaesarComponents/View/Notification/Notification.swift
  Yeowoo/CaesarComponents/View/Notification/NotificationViewModel.swift
  Yeowoo/Configuration/AppDelegate.swift
  Yeowoo/Sources/CaesarComponents/Component/NotiCardContentsView.swift
  Yeowoo/Sources/CaesarComponents/Model/MockupDataModel/Travel.swift
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/FindFriendView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NoticardView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NotificationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/MultiInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleSelectView.swift
  Yeowoo/Sources/CaesarComponents/ViewModel/FindFriendViewModel.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/Views/Auth/LoginCoverView.swift
  Yeowoo/YeowooApp.swift
Labels: ✨ 기능

#60 기능 테스트용 PR
  .DS_Store
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/Main/Album1.imageset/Album1.svg
  Yeowoo/Assets.xcassets/Main/Album1.imageset/Contents.json
  Yeowoo/Assets.xcassets/Main/Album2.imageset/Album2.svg
  Yeowoo/Assets.xcassets/Main/Album2.imageset/Contents.json
  Yeowoo/Assets.xcassets/Main/Album3.imageset/Album3.svg
  Yeowoo/Assets.xcassets/Main/Album3.imageset/Contents.json
  Yeowoo/Assets.xcassets/Main/Album4.imageset/Album4.svg
  Yeowoo/Assets.xcassets/Main/Album4.imageset/Contents.json
  Yeowoo/Assets.xcassets/Onboarding/Contents.json
  Yeowoo/Assets.xcassets/Onboarding/Onboarding1.imageset/Contents.json
  Yeowoo/Assets.xcassets/Onboarding/Onboarding1.imageset/Group 517167120@1x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding1.imageset/Group 517167120@2x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding1.imageset/Group 517167120@3x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding2.imageset/Contents.json
  Yeowoo/Assets.xcassets/Onboarding/Onboarding2.imageset/Group 517167129@1x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding2.imageset/Group 517167129@2x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding2.imageset/Group 517167129@3x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding3.imageset/Contents.json
  Yeowoo/Assets.xcassets/Onboarding/Onboarding3.imageset/Group 517167128@1x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding3.imageset/Group 517167128@2x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding3.imageset/Group 517167128@3x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding4.imageset/Contents.json
  Yeowoo/Assets.xcassets/Onboarding/Onboarding4.imageset/Mask group@1x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding4.imageset/Mask group@2x.png
  Yeowoo/Assets.xcassets/Onboarding/Onboarding4.imageset/Mask group@3x.png
  Yeowoo/Sources/Global/Font+.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/ViewModels/MainViewModel/MainViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/CameraViews/Buttons.swift
  Yeowoo/Sources/Views/CameraViews/CameraButtonView.swift
  Yeowoo/Sources/Views/CameraViews/EditView.swift
  Yeowoo/Sources/Views/CameraViews/WriteTextView.swift
  Yeowoo/Sources/Views/Main/Layouts/AlbumLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
  Yeowoo/Sources/Views/Onboarding/OnboardingView.swift
Labels: ♻️ 리팩토링, ✨ 기능

#62 각종 버그 Fix와 수정사항 적용
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/Main/EmptyCard.imageset/Contents.json
  Yeowoo/Assets.xcassets/Main/EmptyCard.imageset/EmptyCard.svg
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/AlbumRoleSelectView.swift
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/FindFriendView.swift
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/NewAlbumView.swift
  Yeowoo/Sources/CaesarComponents/View/Root/DemoMainView.swift
  Yeowoo/Sources/ViewModels/MainViewModel/MainViewModel.swift
  Yeowoo/Sources/Views/Main/Components/TapePicture.swift
  Yeowoo/Sources/Views/Main/Layouts/AlbumLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/DoneTravelLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
Labels: 🐞 버그, ♻️ 리팩토링
