Repository DeveloperAcademy-POSTECH/MC3-Team5-CleanArea, pull requests merged in 2023-08, with the labels that each got.

#65 2차 테스트 1차 머지
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Info.plist
  Yeowoo/Sources/CaesarComponents/View/PersonalSetting/SettingView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleChangeView.swift
  Yeowoo/Sources/CaesarComponents/ViewModel/FindFriendViewModel.swift
  Yeowoo/Sources/Global/UINavigationController+.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
  Yeowoo/Sources/Views/Album/InviteFriendView.swift
  Yeowoo/Sources/Views/Auth/LoginCoverView.swift
  Yeowoo/Sources/Views/Main/Layouts/BeforeTravelLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/RecommendLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
  Yeowoo/Sources/Views/Onboarding/OnboardingView.swift
Labels: ♻️ 리팩토링, ✨ 기능

#66 2차 수정 머지
  .DS_Store
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Assets.xcassets/EmptyProfile.imageset/Contents.json
  Yeowoo/Assets.xcassets/EmptyProfile.imageset/EmptyProfile.svg
  Yeowoo/Assets.xcassets/Person/Azhy.imageset/Contents.json
  Yeowoo/Sources/CaesarComponents/View/PersonalSetting/ProfileSettingView.swift
  Yeowoo/Sources/CaesarComponents/View/PersonalSetting/SettingView.swift
  Yeowoo/Sources/ContentView.swift
  Yeowoo/Sources/ViewModels/MainViewModel/MainViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
  Yeowoo/Sources/Views/CameraViews/WriteTextView.swift
  Yeowoo/Sources/Views/Main/Components/Person.swift
  Yeowoo/Sources/Views/Main/Layouts/AlbumLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
  Yeowoo/Sources/Views/Onboarding/OnboardingView.swift
Labels: 🐞 버그, ♻️ 리팩토링

#67 2차 테스트 2차 머지
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Sources/CaesarComponents/Component/NotiCardContentsView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NotificationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/MultiInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleChangeView.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/AlbumViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
Labels: 🐞 버그, ♻️ 리팩토링, ✨ 기능

#68 3차 버그 수정 머지
  .DS_Store
  Yeowoo.xcodeproj/project.pbxproj
  Yeowoo/Sources/CaesarComponents/Component/NotiCardContentsView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NoticardView.swift
  Yeowoo/Sources/CaesarComponents/View/Notification/NotiChildView/NotificationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/MultiInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationChildView/TwoInvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/InvitationView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleSelectView.swift
  Yeowoo/Sources/Views/CameraViews/WriteTextView.swift
  Yeowoo/Sources/Views/Main/MainView.swift
Labels: 🐞 버그, ♻️ 리팩토링, ✨ 기능

#69 유저 테스트 이후 나타난 버그 수정
  .DS_Store
  Yeowoo/Assets.xcassets/Main/EmptyFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Main/EmptyFox.imageset/EmptyFox.svg
  Yeowoo/Assets.xcassets/Main/PackFox.imageset/Contents.json
  Yeowoo/Assets.xcassets/Main/PackFox.imageset/EmptyFox@1x.png
  Yeowoo/Assets.xcassets/Main/PackFox.imageset/EmptyFox@2x.png
  Yeowoo/Assets.xcassets/Main/PackFox.imageset/EmptyFox@3x.png
  Yeowoo/Assets.xcassets/Person/Azhy.imageset/.DS_Store
  Yeowoo/Sources/CaesarComponents/View/NewAlbum/FindFriendView.swift
  Yeowoo/Sources/CaesarComponents/View/Role/RoleChangeView.swift
  Yeowoo/Sources/Services/Firebase/FirebaseService.swift
  Yeowoo/Sources/ViewModels/MainViewModel/MainViewModel.swift
  Yeowoo/Sources/Views/Album/AlbumDetailView.swift
  Yeowoo/Sources/Views/Album/AlbumFeedView.swift
  Yeowoo/Sources/Views/Album/Layouts/FirstFeedLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/GalleryLayout.swift
  Yeowoo/Sources/Views/Album/Layouts/SecondFeedLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/BeforeTravelLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/NoAlbumLayout.swift
  Yeowoo/Sources/Views/Main/Layouts/RecommendLayout.swift
  Yeowoo/Sources/Views/Main/MainView.swift
Labels: 🐞 버그, ♻️ 리팩토링, ✨ 기능
